In [ ]:
### Name: Arinjay Jain (A20447307)
## Class: CS 577
## Homework 0 

In [37]:
%config IPCompleter.greedy=True
#Part A
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([-1,1,3])

In [38]:
#Question A-1
np.dot(2,A) - B

array([-2, -1,  0])

In [60]:
#Question A-2
megA = np.linalg.norm(A)
print(megA)
angleWithX = np.arccos(A[0]/megA)
import math
angleWithX*180/math.pi

3.7416573867739413


74.498640433063

In [61]:
#Question A-3
A_hat = A/ megA
print(A_hat)

[0.26726124 0.53452248 0.80178373]


In [62]:
#Question A-4
#The coordinates of the unit vector is equal to its direction cosines.
# Same as A_hat
print(A_hat)

[0.26726124 0.53452248 0.80178373]


In [63]:
#Question A-5
# Dot product of A.B = B.A because they are single row vector
AB = np.dot(A,B)
print(AB)

32


In [64]:
#Question A-6
angleAB = np.arccos(AB/(megA*np.linalg.norm(B)))
print(angleAB)
angleAB*180/math.pi

0.2257261285527342


12.933154491899135

In [65]:
#Question A-7
print(BXA)
#BXA is one of perpendicular vector of A

[ 3 -6  3]


In [66]:
#Question A-8
AXB = np.cross(A,B)
print(AXB)
BXA = np.cross(B,A)
print(BXA)

[-3  6 -3]
[ 3 -6  3]


In [67]:
#Question A-9
# AXB is a perpendicular vector of A and B
print(AXB)

[-3  6 -3]


In [68]:
#Question A-10
mat = np.array([A,B,C])
print(np.linalg.det(mat))
print("There exists linear dependency between A, B and C as the determinant of the matrix is 0")

7.494005416219837e-16
There exists linear dependency between A, B and C as the determinant of the matrix is 0


In [94]:
#Question A-11
A.shape=(3,1)
B.shape=(3,1)
C.shape=(3,1)
AT=A.transpose()
ATB = np.dot(AT,B)
print(ATB)
BT = B.transpose()
ABT = np.dot(A,BT)
print(ABT)

[[32]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [14]:
A = np.array([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.array([[1,2,3],[4,5,6],[-1,1,3]])

In [4]:
#Question B-1
np.dot(2,A) - B

array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

In [5]:
#Question B-2
# Dot product of A.B
AB = np.dot(A,B)
print(AB)

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]


In [6]:
# Dot product of B.A
BA = np.dot(B,A)
print(BA)

[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [7]:
#Question B-3
# Dot product of (AB)T = BT.AT
ABT = AB.transpose()
print(ABT)

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [8]:
#Question B-4
detA = np.linalg.det(A)
print(detA)
detC = np.linalg.det(C)
print(detC)

54.999999999999964
7.494005416219837e-16


In [18]:
#Question B-5
def orthogonal(A):
    product = np.dot(A,A.T)
    np.fill_diagonal(product,0)
    if (product.any() == 0):
        print("Matrix the row vectors form an orthogonal set", A)
orthogonal(A)
orthogonal(B)
orthogonal(C)

Matrix the row vectors form an orthogonal set [[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]


In [21]:
#Question B-6
invA = np.linalg.inv(A)
print("Inverse of matrix A:",invA)
invB = np.linalg.inv(B)
print("Inverse of matrix B:",invB)

Inverse of matrix A: [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
Inverse of matrix B: [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [24]:
#Part-C 
#Question C-1
import numpy as np
A = np.array([[1,2],[3,2]])
B = np.array([[2,-2],[-2,5]])


In [26]:
e, v = np.linalg.eig(A)
print(e)
print(v)

[-1.  4.]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [27]:
V = v
print(V)

[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [30]:
#Question C-2
Vinv = np.linalg.inv(V)
VinvA = np.dot(Vinv,A)
VinvAV = np.dot(VinvA,V)
print(VinvAV)

[[-1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  4.0000000e+00]]


In [32]:
#Question C-3 dot product between the eigenvectors of A
eigdotA = np.dot(V[0],V[1])
print(eigdotA)

-0.038461538461538214


In [35]:
#Question C-4 dot product between the eigenvectors of B
eB, vB = np.linalg.eig(B)
print("Eigin Value:", eB)
eigdotB = np.dot(vB[0],vB[1])
print("Dot Product between the eigenvectors of B:",eigdotB)

Eigin Value: [1. 6.]
Dot Product between the eigenvectors of B: 0.0


In [36]:
# Question C-5 #The property of the eigenvectors of B and its reason.
print("We can see dot between the eigenvectors of B is Zero, So we can say Eigen vectors are orthogonal to each other.")

We can see dot between the eigenvectors of B is Zero, So we can say Eigen vectors are orthogonal to each other.
